# TODO: Define the Workflow Name
name: devops-workflow

# TODO: Define triggers for the workflow
on:
   push:
     branches: master 
   pull_request:
     branches: master

jobs:
  # TODO: Define a job for building and testing the frontend
  frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      # TODO: Checkout code
      # TODO: Setup Node.js
      # TODO: Install dependencies
      # Run tests
    - name: Test code
      run: npm run test
   # - name: Test Setup
   #   run: node Project/frontend/src/setupTests.js
      # TODO: Build the React app
  backend:
    runs-on: ubuntu-latest
    steps:
    
    
      # Checkout code
    - name: Checkout repo
      uses: actions/checkout@v2
      # Setup Python
    - name: Setup Python
      uses: actions/setup-node@v2
      with:
       python-version: '3.9'
      
      # Run tests
    - name: Test backend
      run: pytest

  # TODO: Define a job for building and pushing Docker images
