# TODO: Define the Workflow Name
name: devops-workflow

# TODO: Define triggers for the workflow
on:
   push:
     branches: master 
   pull_request:
     branches: master

jobs:
  # TODO: Define a job for building and testing the frontend
  frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
      # Setup Node.js
        node-version: '14'

      # TODO: Install dependencies
    - name: Install dependencies
      run: npm install
      working-directory: ./Project/frontend/
    # - name: Running tests
    #   run: npm run test
    #   working-directory: ./Project/frontend/

    - name: Build code
      run: npm run build
      working-directory: ./Project/frontend/
  backend:
    needs: frontend
    runs-on: ubuntu-latest
    steps:
    
    
      # Checkout code
    - name: Checkout repo
      uses: actions/checkout@v2
      # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
       python-version: '3.9'
      # Install dependencies
    - name: Install python dependencies
      run : pip install -r requirements.txt
      working-directory: ./Project/backend/
      # Run tests
    - name: Test backend
      run: pytest
      working-directory: ./Project/backend/

  # TODO: Define a job for building and pushing Docker images
